seed_everything: 42
model:
  class_path: methods.dcmcs3di.DCMCS3DI
  init_args:
    extraction_layers: 18
    transfer_layers: 6
    channels: 64
data:
  class_path: utils.data.DataModule
  init_args:
    data_dir: Artificial Dataset
    crop_size: [160, 320]
    image_repeats: 37
    batch_size: 8
    num_workers: 32
trainer:
  max_epochs: 100
  logger:
      class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: color-transfer
        log_model: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: Validation PSNR
        mode: max
