seed_everything: 42
model:
  class_path: methods.dct.TrainDeepColorTransfer
  init_args:
    max_hw: 131072
data:
  class_path: utils.data.DataModule
  init_args:
    data_dir: Artificial Dataset
    crop_size: [256, 512]
    batch_size: 8
    num_workers: 8
trainer:
  max_epochs: 100
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: color-transfer
      log_model: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: Validation PSNR
        mode: max