seed_everything: 42
model:
  class_path: methods.dmsct.DMSCT
  init_args:
    encoder_name: efficientnet-b2
    encoder_depth: 4
    encoder_weights: null
    decoder_channels: [256, 128, 64, 32]
data:
  class_path: utils.data.DataModule
  init_args:
    data_dir: Artificial Dataset
    crop_size: [256, 480]
    batch_size: 12
    num_workers: 32
trainer:
  max_epochs: 100
  logger:
      class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: color-transfer
        log_model: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: Validation PSNR
        mode: max
