seed_everything: 42
model:
  class_path: methods.dmsct.TrainDeepColorTransfer
  init_args:
    batch_size: 2
    patch_shape: [128, 128]
data:
  class_path: utils.data.DataModule
  init_args:
    data_dir: Artificial Dataset
    batch_size: 8
    num_workers: 0
trainer:
  max_epochs: 1